# Site settings
title: Dcyclebox 7
header-img: img/dcyclebox.png
email: no-monitored@dcycle.com
description: "A Docker-based workflow for Drupal and Jekyll development, testing, continuous integration and deployment."
baseurl: ""
url: "http://box.dcycle.com/"
twitter_username: dcycleproject
github_username:  dcycleproject

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 99
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
