# See https://github.com/alberto56/docker-drupal
FROM alberto56/docker-drupal:8.0.x-dev-1.2-8.0.0-beta10

# See http://dcycleproject.org/blog/68/approach-code-driven-development-drupal-8
RUN cd /srv/drupal/www && echo '$'"config_directories['deploy'] = '../deploy';" >> sites/default/settings.php

ADD ./deploy /srv/drupal/deploy
ADD ./drupal/modules /srv/drupal/www/modules/
ADD ./drupal/themes /srv/drupal/www/themes/
ADD ./dcycle/container-scripts /srv/drupal/scripts/
ADD ./Dcycle-settings.sh /srv/drupal/scripts/Dcycle-settings.sh

# We will want to link the /db folder to the host, but upon doing so with the -v
# flag, Docker will copy the contents of the local folder to the container.
# If said contents do not exist, we will want to grab /tmp/database
RUN mv /db/.ht.sqlite /tmp/initial-database
